---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vprodb-pv
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0f650808478b5d76d
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vprodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: us-east-2a
      containers:
        - name: vprodb
          image: piyush1337/vprofiledb:v1
          args:
            - "--ignore-db-dir=lost+found"
          ports:
            - containerPort: 3306
              name: vprodb-port
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: vpro-db-data
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-pass
      volumes:
        - name: vpro-db-data
          persistentVolumeClaim:
            claimName: vprodb-pvc
